

services:
  postgresbookingdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: user0
      POSTGRES_PASSWORD: 240240
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminbooking
    restart: always
    ports:
      - "8089:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nguyenngockhanh240@gmail.com
      PGADMIN_DEFAULT_PASSWORD: N0pe.avi240

  app:
    image: my-springboot-app:latest  # Use the existing image name
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - pgadminbooking
    

volumes:
  pgdata:

